site_name: Warhammer 40 000 conversion
site_url: https://DrDam.github.io/dnd2w40k/
theme:
  name: material
  features:
    - navigation.expand
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 2

nav:
  - A propos : index.md
  - Note préliminaire : 0-disclaimer.md
  - "Livre 1 : Manuel du joueur":
      - 1. Préambule: I.Manuel-joueur/0-preambule.md
      - 2. Les personnages, étape par étape: I.Manuel-joueur/1-perso.md
      - 3. Les espèces:
        - Les Espèces: I.Manuel-joueur/Especes/0-especes.md
        - L'humanité:
            - A propos : I.Manuel-joueur/Especes/1-Humanite.md
            - Les Blanks: I.Manuel-joueur/Especes/2-Blank.md
            - Les Corrompus: I.Manuel-joueur/Especes/2-Corrompus.md
            - Les hommes-bêtes: I.Manuel-joueur/Especes/2-Homme-betes.md
            - Les humains: I.Manuel-joueur/Especes/2-Humain.md
            - Les Mutants: I.Manuel-joueur/Especes/2-Mutant.md
            - Les Ogryns: I.Manuel-joueur/Especes/2-Ogryn.md
            - Les Ratlings: I.Manuel-joueur/Especes/2-Ratling.md
            - Les Scouts SpaceMarines: I.Manuel-joueur/Especes/2-Scout.md
            - Les Technofusionnés: I.Manuel-joueur/Especes/2-Techfused.md
        - Xenos:
            - A propos : I.Manuel-joueur/Especes/3-xenos.md
            - Les Aeldari : I.Manuel-joueur/Especes/4-Aeldari.md
            - Les Cognats: I.Manuel-joueur/Especes/4-Cognat.md
  - "Livre 2 : Manuel du Maitre du jeu":
      - avant-propos: II.Manuel-MJ/index.md
  - "Livre 3 : Manuel des montres":
      - avant-propos: III.Manuel-Monstres/index.md
  - Credits : credits.md

extra_css:
  - stylesheets/extra.css
