site_name: Warhammer 40 000 conversion
site_url: https://DrDam.github.io/dnd2w40k/
theme:
  name: material
  features:
    - navigation.expand
    - toc.integrate

markdown_extensions:
  - toc:
      toc_depth: 2

