site_name: Warhammer 40 000 conversion
site_url: https://DrDam.github.io/dnd2w40k/
theme:
  name: material
  features:
    - navigation.expand
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 2

extra_css:
  - stylesheets/extra.css

hooks:
  - docs/hooks/colspan_tables.py



nav:
  - A propos : index.md
  - Note préliminaire : 0-disclaimer.md
  - "Livre 1 : Manuel du joueur":
      - 1. Préambule: I.Manuel-joueur/0-preambule.md
      - 2. Les personnages, étape par étape: I.Manuel-joueur/1-perso.md
      - 3. Les espèces - L'humanité :
        - A propos : I.Manuel-joueur/Especes/1-Humanite.md
        - Les Blanks: I.Manuel-joueur/Especes/2-Blank.md
        - Les Corrompus: I.Manuel-joueur/Especes/2-Corrompus.md
        - Les hommes-bêtes: I.Manuel-joueur/Especes/2-Homme-bete.md
        - Les humains: I.Manuel-joueur/Especes/2-Humain.md
        - Les Mutants: I.Manuel-joueur/Especes/2-Mutant.md
        - Les Ogryns: I.Manuel-joueur/Especes/2-Ogryn.md
        - Les Ratlings: I.Manuel-joueur/Especes/2-Ratling.md
        - Les Technofusionnés: I.Manuel-joueur/Especes/2-Techfused.md
      - 4. Les Espèces - Les Xenos:
        - A propos : I.Manuel-joueur/Especes/3-Xenos.md
        - Les Aeldari : I.Manuel-joueur/Especes/4-Aeldari.md
        - Les Cognats: I.Manuel-joueur/Especes/4-Cognat.md
        - Les Genestealers: I.Manuel-joueur/Especes/4-Genestealers.md
        - Les Hommes-Rats: I.Manuel-joueur/Especes/4-Hommes-rats.md
        - Les Gretchins: I.Manuel-joueur/Especes/4-Gretchin.md
        - Les Jokaeros: I.Manuel-joueur/Especes/4-Jokaero.md
        - Les Kroots: I.Manuel-joueur/Especes/4-Kroot.md
        - Les Lacrymoles: I.Manuel-joueur/Especes/4-Lacrymole.md
        - Les Necrons: I.Manuel-joueur/Especes/4-Necron.md
        - Les Orks: I.Manuel-joueur/Especes/4-Ork.md
        - Les Stryxis: I.Manuel-joueur/Especes/4-Stryxis.md
        - Les Tarellians: I.Manuel-joueur/Especes/4-Tarellian.md
        - Les Tau: I.Manuel-joueur/Especes/4-Tau.md
        - Les Thyrrus: I.Manuel-joueur/Especes/4-Thyrrus.md
        - Les Vespides: I.Manuel-joueur/Especes/4-Vespide.md
        - Les Viskeons: I.Manuel-joueur/Especes/4-Viskeon.md
      - 5. Les Space Marines:
        - A propos : I.Manuel-joueur/Especes/5-SpaceMarines.md
        - Les Scouts Space Marines: I.Manuel-joueur/Especes/6-Scout.md
        - Les Space Marines: I.Manuel-joueur/Especes/6-SpaceMarine.md
      - 6. Les classes:
        - les classes: I.Manuel-joueur/Classes/0-Classes.md
        - les Agents: I.Manuel-joueur/Classes/1-Agent.md
        - les Augmentistes: I.Manuel-joueur/Classes/1-Augmentiste.md
        - les Berserkers : I.Manuel-joueur/Classes/1-Berserker.md
        - les Croisés : I.Manuel-joueur/Classes/1-Croise.md
        - les Exorcistes : I.Manuel-joueur/Classes/1-Exorciste.md
        - les Mécaniciens : I.Manuel-joueur/Classes/1-Mecanicien.md
        - les Psykers : I.Manuel-joueur/Classes/1-Psyker.md
        - les Soldats : I.Manuel-joueur/Classes/1-Soldat.md
        - les Sorciers : I.Manuel-joueur/Classes/1-Sorcier.md
        - les Traqueurs : I.Manuel-joueur/Classes/1-Traqueur.md
      - 7. Personnalité et historique:
        - Préambule: I.Manuel-joueur/Origines/0-title.md
        - les Langues: I.Manuel-joueur/Origines/1-Langues.md
        - les Historiques: I.Manuel-joueur/Origines/2-Historiques.md
        - les Chapitre/Légion: I.Manuel-joueur/Origines/3-OrigineSM.md
        - les Roles opérationnels: I.Manuel-joueur/Origines/4-RoleOperationnel.md
      - 8. Équipement:
        - Préambule: I.Manuel-joueur/Equipement/0-index.md
        - les Armures: I.Manuel-joueur/Equipement/1-armures.md
        - les Armes: I.Manuel-joueur/Equipement/2-armes.md
        - les Équipement d'aventuriers: I.Manuel-joueur/Equipement/3-Equipement-aventure.md
        - les Outils: I.Manuel-joueur/Equipement/4-Outils.md
        - les Marchandises: I.Manuel-joueur/Equipement/5-Marchandises.md
      - 9. Options de personnalisation:
        - Préambule: I.Manuel-joueur/Personalisation/0-intro.md
        - le multiclassage: I.Manuel-joueur/Personalisation/1-multiclasse.md
        - les Dons: I.Manuel-joueur/Personalisation/2-dons.md
  - "Livre 2 : Manuel du Maitre du jeu":
      - avant-propos: II.Manuel-MJ/0-index.md
      - les équipements avancés: II.Manuel-MJ/2-Equipement-avance.md
  - "Livre 3 : Manuel des montres":
      - avant-propos: III.Manuel-Monstres/index.md
  - Credits : credits.md

