name: Build

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          pip install mkdocs mkdocs-material beautifulsoup4 pillow --break-system-packages
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Build MkDocs
        run: |
          chmod +x tools/mkdocs/build_site.sh
          chmod +x tools/mkdocs/build_all_site.sh
          ./tools/mkdocs/build_all_site

      - name: Build PDF
        run: |
          chmod +x tools/book/book.sh
          chmod +x tools/book/build_all_books.sh
          ./tools/book/build_all_books.sh

      - name: Move PDF into MkDocs
        run: |
          mkdir -p site/assets/pdf
          cp build/*.pdf site/assets/pdf/

      - name: Deploy wiki
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
